services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: project_ticket_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-migration/db-init.sql:/docker-entrypoint-initdb.d/00_db-init.sql:ro
      - ./db-migration/V202603080001__create_ticket_work_logs.sql:/docker-entrypoint-initdb.d/01_create_ticket_work_logs.sql:ro
      - ./db-migration/V202603081225__update_display_name_to_users.sql:/docker-entrypoint-initdb.d/02_update_display_name.sql:ro
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    depends_on:
      - db
    environment:
      PORT: 4000
      DATABASE_URL: postgres://postgres:postgres@db:5432/project_ticket_management
      CLIENT_ORIGIN: http://localhost:4200
      DB_SSL: 'false'
    ports:
      - "4000:4000"

volumes:
  db-data:
